name: flutter_first
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.6.0

dependencies:
  shared_preferences: ^2.1.1
  flutter:
    sdk: flutter
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.6.1
  http: ^1.1.0
  timeline_tile: ^2.0.0
  shimmer: ^3.0.0
  lottie: ^3.3.0
  connectivity_plus: ^6.1.1
  logger: ^2.5.0
  logging: ^1.3.0
  pdf: ^3.10.7
  path_provider: ^2.1.2
  open_file: ^3.3.2
  url_launcher: ^6.3.1
  csv: ^6.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: "^0.14.3"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/login.png
    - assets/rafi.jpg
    - assets/crown.png
    - assets/splash.gif
    - assets/studentRank39NFE.csv
    - assets/studentRank61CSE.csv
    - lib\assets\Images\shakib_dev.jpg
    - assets/signup.json
    - assets/login.json
    - assets/reset.json