// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaEgHI0YIb0Tw9sSexUTwHGqPQFIdQBfg',
    appId: '1:307367250704:web:b245c56a44c8ea8607f395',
    messagingSenderId: '307367250704',
    projectId: 'diu-leaderboard-9c0e0',
    authDomain: 'diu-leaderboard-9c0e0.firebaseapp.com',
    storageBucket: 'diu-leaderboard-9c0e0.firebasestorage.app',
    measurementId: 'G-14G7LXDH7N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDn-C-JEKMUfvfWW0VCL48o7I69Q_ZUlss',
    appId: '1:307367250704:android:eca9f27f0bae165107f395',
    messagingSenderId: '307367250704',
    projectId: 'diu-leaderboard-9c0e0',
    storageBucket: 'diu-leaderboard-9c0e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0UgTc9VzLGdn-iTx1aPPyUqcUBk5hixw',
    appId: '1:307367250704:ios:631c130282cc0b0007f395',
    messagingSenderId: '307367250704',
    projectId: 'diu-leaderboard-9c0e0',
    storageBucket: 'diu-leaderboard-9c0e0.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyPPd707ii4SVanJpkCa_U4iJji0Psg10',
    appId: '1:403149345679:ios:171061591c4dd5e605f1fa',
    messagingSenderId: '403149345679',
    projectId: 'diu-leaderboard',
    storageBucket: 'diu-leaderboard.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8tedA3oj-RP_lBnsGulwVNwBxUNNRuWA',
    appId: '1:403149345679:web:fca3563e33d1b70105f1fa',
    messagingSenderId: '403149345679',
    projectId: 'diu-leaderboard',
    authDomain: 'diu-leaderboard.firebaseapp.com',
    storageBucket: 'diu-leaderboard.firebasestorage.app',
    measurementId: 'G-GF3BNXVFV2',
  );
}