// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8tedA3oj-RP_lBnsGulwVNwBxUNNRuWA',
    appId: '1:403149345679:web:993f68cdb4f51cc505f1fa',
    messagingSenderId: '403149345679',
    projectId: 'diu-leaderboard',
    authDomain: 'diu-leaderboard.firebaseapp.com',
    storageBucket: 'diu-leaderboard.firebasestorage.app',
    measurementId: 'G-9RVDMB6M0C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3j7s5I2sARbhJaEI_4SX_R9R7Yl5Ztic',
    appId: '1:403149345679:android:9e182bd87c2a1e1805f1fa',
    messagingSenderId: '403149345679',
    projectId: 'diu-leaderboard',
    storageBucket: 'diu-leaderboard.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyPPd707ii4SVanJpkCa_U4iJji0Psg10',
    appId: '1:403149345679:ios:171061591c4dd5e605f1fa',
    messagingSenderId: '403149345679',
    projectId: 'diu-leaderboard',
    storageBucket: 'diu-leaderboard.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyPPd707ii4SVanJpkCa_U4iJji0Psg10',
    appId: '1:403149345679:ios:171061591c4dd5e605f1fa',
    messagingSenderId: '403149345679',
    projectId: 'diu-leaderboard',
    storageBucket: 'diu-leaderboard.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8tedA3oj-RP_lBnsGulwVNwBxUNNRuWA',
    appId: '1:403149345679:web:fca3563e33d1b70105f1fa',
    messagingSenderId: '403149345679',
    projectId: 'diu-leaderboard',
    authDomain: 'diu-leaderboard.firebaseapp.com',
    storageBucket: 'diu-leaderboard.firebasestorage.app',
    measurementId: 'G-GF3BNXVFV2',
  );
}
